### ISSUE TITLE
not a streamable links

### ISSUE THREAD

**Issue by jhaylee2016** [ArdiArtani/Google-Drive-Player-Script#37] opened 2017-09-01 16:46 UTC
i mean this script does not provide redirector link...

**Comment by RiseCoder** [comment] 2017-09-01 19:34
Google Drive and Other Platform Player Api Service

Fast, secure, fixed price guarantee.

Supports: Google Drive, Google Photos, Youtube, Vimeo, Vid.me, Dropbox

Demo: http://www.playersapi.com

Our API currently costs roughly $1 per 1,000 requests. Requests for the same link within an day are not charged.

Skype : api@playersapi.com

**Comment by jhaylee2016** [comment] 2017-09-01 20:02
@RiseCoder im sorry im not interested..by the way thanks for the offer...i already have those script except google drive...

**Comment by threathgfx** [comment] 2017-09-02 00:28
@jhaylee2016 this script is still inprogress.

**Comment by Zebraslive** [comment] 2017-09-18 00:45
Anyone know what he google.mp3 is for? do i need it?

**Comment by milankragujevic** [comment] 2017-09-18 08:14
@Zebraslive It's cookie storage, you do need it.

**Comment by ArdiArtani** [comment] 2017-09-25 16:16
Duplicate of #7

**Closed by ArdiArtani** 2017-09-25 16:16 UTC
